version: "3"

services:
  api:
    container_name: api_server
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - backend
      - redis

  backend:
    container_name: backend_server
    build: ./backend
    ports:
      - 50051:50051
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/etc/mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  grpc-gateway:
    container_name: grpc-gateway
    build: ./grpc-gateway
    ports:
      - 8081:8081
    environment:
      ENDPOINT: backend:50051
    depends_on:
      - backend
